BLN.BIS_LIST_S1 = {
    ["Demon Hunter"] = {
        ["Havoc"] = {
            --D
            [221163] = { itemName = "Whispering Mask" },
            [178707] = { itemName = "Trailspinner Pendant" },
            [221094] = { itemName = "Whispering Umbral Mantle" },
            [133363] = { itemName = "Troggstitched Drape" },
            [133297] = { itemName = "Vest of Misshapen Hides" },
            [221157] = { itemName = "Unbreakable Beetlebane Bindings" },
            [221180] = { itemName = "Gorebound Stranglers" },
            [221134] = { itemName = "Shadow Congregant's Belt" },
            [221153] = { itemName = "Gauzewoven Legguards" },
            [221169] = { itemName = "Whisperer's Echoing Steps" },
            [221136] = { itemName = "Devout Zealot's Ring" },
            [162542] = { itemName = "Seal of the City Watch" },
            [133282] = { itemName = "Skardyn's Grace" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [159651] = { itemName = "Coral-Edged Crescent" },
            [221160] = { itemName = "Blight Hunter's Scalpelglaive" },
            --R
            [212448] = { itemName = "Locket of Broken Memories" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [212438] = { itemName = "Polluted Spectre's Wraps" },
            [212432] = { itemName = "Thousand-Scar Impalers" },
            [225583] = { itemName = "Behemoth's Eroded Cinch" },
            [212445] = { itemName = "Chitin-Spiked Jackboots" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [212447] = { itemName = "Key to the Unseeming" },
            [212454] = { itemName = "Mad Queen's Mandate" },
            [212456] = { itemName = "Void Reaper's Contract" },
            [219877] = { itemName = "Void Reaper's Warp Blade" },
            [212391] = { itemName = "Predator's Feasthooks" },
        },
        ["Vengeance"] = {
            --D
            [221081] = { itemName = "Guise of the Construct" },
            [221181] = { itemName = "Elder's Hemolymphal Periapt" },
            [133292] = { itemName = "Azureborne Cloak" },
            [221142] = { itemName = "Scheming Assailer's Bands" },
            [159309] = { itemName = "Port Pillager's Belt" },
            [159320] = { itemName = "Besieger's Deckstalkers" },
            [221136] = { itemName = "Devout Zealot's Ring" },
            [159461] = { itemName = "Band of the Ancient Dredger" },
            [178742] = { itemName = "Bottled Flayedwing Toxin" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [219312] = { itemName = "Empowering Crystal of Anub'ikkaj" },
            [221090] = { itemName = "Eirich's Fist of Deception" },
            [221084] = { itemName = "Skardyn Mercybringer" },
            --R
            [212417] = { itemName = "Beyond's Dark Visage" },
            [212448] = { itemName = "Locket of Broken Memories" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [225588] = { itemName = "Sanguine Experiment's Bandages" },
            [225583] = { itemName = "Behemoth's Eroded Cinch" },
            [212445] = { itemName = "Chitin-Spiked Jackboots" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [212447] = { itemName = "Key to the Unseeming" },
            [212449] = { itemName = "Sikran's Endless Arsenal" },
            [212456] = { itemName = "Void Reaper's Contract" },
            [219915] = { itemName = "Foul Behemoth's Chelicera" },
            [219877] = { itemName = "Void Reaper's Warp Blade" },
            [212409] = { itemName = "Venom-Etched Claw" },
        },
    },
    ["Death Knight"] = {
        ["Blood"] = {
            --D
            [221146] = { itemName = "Soaring Behemoth's Greathelm" },
            [178707] = { itemName = "Trailspinner Pendant" },
            [133294] = { itemName = "Earthshape Pauldrons" },
            [221154] = { itemName = "Swarmcaller's Shroud" },
            [221139] = { itemName = "Dark Priest's Carapace" },
            [133306] = { itemName = "Bracers of Umbral Mending" },
            [221086] = { itemName = "Machinist's Searing Handguards" },
            [159434] = { itemName = "Cannoneer's Toolbelt" },
            [221092] = { itemName = "Legplates of Broken Trust" },
            [221178] = { itemName = "Ichor-Stained Sollerets" },
            [162541] = { itemName = "Band of the Roving Scalawag" },
            [178781] = { itemName = "Ritual Commander's Ring" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [178751] = { itemName = "Spare Meat Hook" },
            [159650] = { itemName = "Dismembered Submersible Claw" },
            --R
            [212427] = { itemName = "Visor of the Ascended Captain" },
            [225575] = { itemName = "Silken Advisor's Favor" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [225587] = { itemName = "Devoted Offering's Irons" },
            [222431] = { itemName = "Everforged Greatbelt" },
            [222429] = { itemName = "Everforged Sabatons" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [225576] = { itemName = "Writhing Ringworm" },
            [212453] = { itemName = "Skyterror's Corrosive Organ" },
            [212449] = { itemName = "Sikran's Endless Arsenal" },
            [212407] = { itemName = "Anub'arash's Colossal Mandible" },
        },
        ["Frost"] = {
            --D
            [178694] = { itemName = "Wrathbark Greathelm" },
            [178707] = { itemName = "Trailspinner Pendant" },
            [221185] = { itemName = "Flesh Connector's Epaulets" },
            [133363] = { itemName = "Troggstitched Drape" },
            [221139] = { itemName = "Dark Priest's Carapace" },
            [133306] = { itemName = "Bracers of Umbral Mending" },
            [178706] = { itemName = "Fogweaver Gauntlets" },
            [221079] = { itemName = "Crystal-Fissure Girdle" },
            [178739] = { itemName = "Legplates of Unholy Frenzy" },
            [159428] = { itemName = "Ballast Sinkers" },
            [221136] = { itemName = "Devout Zealot's Ring" },
            [162541] = { itemName = "Band of the Roving Scalawag" },
            [219300] = { itemName = "Skarmorak Shard" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [221145] = { itemName = "Shipwrecker's Bludgeon" },
            --R
            [212427] = { itemName = "Visor of the Ascended Captain" },
            [212448] = { itemName = "Locket of Broken Memories" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [225587] = { itemName = "Devoted Offering's Irons" },
            [225589] = { itemName = "Nether Bounty's Greatbelt" },
            [225590] = { itemName = "Boots of the Black Bulwark" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [225576] = { itemName = "Writhing Ringworm" },
            [220305] = { itemName = "Ovi'nax's Mercurial Egg" },
            [221023] = { itemName = "Treacherous Transmitter" },
            [212401] = { itemName = "Ansurek's Final Judgment" },
        },
        ["Unholy"] = {
            --D
            [178694] = { itemName = "Wrathbark Greathelm" },
            [221077] = { itemName = '"Emergency Stop" Keychain' },
            [221088] = { itemName = "Anvilhide Cape" },
            [133306] = { itemName = "Bracers of Umbral Mending" },
            [221133] = { itemName = "Girdle of Somber Ploys" },
            [159428] = { itemName = "Ballast Sinkers" },
            [178736] = { itemName = "Stitchflesh's Misplaced Signet" },
            [133299] = { itemName = "Circle of Bone" },
            [133300] = { itemName = "Mark of Khardros" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [56131] = { itemName = "Wild Hammer" },
            --R
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [225587] = { itemName = "Devoted Offering's Irons" },
            [225589] = { itemName = "Nether Bounty's Greatbelt" },
            [225590] = { itemName = "Boots of the Black Bulwark" },
            [225576] = { itemName = "Writhing Ringworm" },
            [212447] = { itemName = "Key to the Unseeming" },
            [221023] = { itemName = "Treacherous Transmitter" },
            [220305] = { itemName = "Ovi'nax's Mercurial Egg" },
            [212388] = { itemName = "Ulgrax's Morsel-Masher" },
        },
    },
    ["Druid"] = {
        ["Balance"] = {
            --D
            [221163] = { itemName = "Whispering Mask" },
            [221077] = { itemName = '"Emergency Stop"' },
            [221088] = { itemName = "Anvilhide Cape" },
            [221157] = { itemName = "Unbreakable Beetlebane Bindings" },
            [221134] = { itemName = "Shadow Congregant's Belt" },
            [221169] = { itemName = "Whisperer's Echoing Steps" },
            [133286] = { itemName = "Umbriss Band" },
            [133299] = { itemName = "Circle of Bone" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [133304] = { itemName = "Gale of Shadows" },
            [221085] = { itemName = "Melodious Iron Songspire" },
            --R
            [212417] = { itemName = "Beyond's Dark Visage" },
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [212446] = { itemName = "Royal Emblem of Nerub-ar" },
            [212438] = { itemName = "Polluted Spectre's Wraps" },
            [212425] = { itemName = "Devourer's Taut Innards" },
            [212445] = { itemName = "Chitin-Spiked Jackboots" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [220305] = { itemName = "Ovi'nax's Mercurial Egg" },
            [220202] = { itemName = "Spymaster's Web" },
            [212397] = { itemName = "Takazj's Entropic Edict" },
        },
        ["Feral"] = {
            --D
            [178707] = { itemName = "Trailspinner Pendant" },
            [221088] = { itemName = "Anvilhide Cape" },
            [221142] = { itemName = "Scheming Assailer's Bands" },
            [221180] = { itemName = "Gorebound Stranglers" },
            [221134] = { itemName = "Shadow Congregant's Belt" },
            [221169] = { itemName = "Whisperer's Echoing Steps" },
            [133299] = { itemName = "Circle of Bone" },
            [133286] = { itemName = "Umbriss Band" },
            [133282] = { itemName = "Skardyn's Grace" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [221159] = { itemName = "Harvester's Interdiction" },
            --R
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [212438] = { itemName = "Polluted Spectre's Wraps" },
            [212432] = { itemName = "Thousand-Scar Impalers" },
            [225583] = { itemName = "Behemoth's Eroded Cinch" },
            [212445] = { itemName = "Chitin-Spiked Jackboots" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [225576] = { itemName = "Writhing Ringworm" },
            [221023] = { itemName = "Treacherous Transmitter" },
            [212454] = { itemName = "Mad Queen's Mandate" },
            [212413] = { itemName = "Honored Executioner's Perforator" },
        },
        ["Guardian"] = {
            --D
            [178691] = { itemName = "Hood of the Hidden Path" },
            [221181] = { itemName = "Elder's Hemolymphal Periapt" },
            [221154] = { itemName = "Swarmcaller's Shroud" },
            [178741] = { itemName = "Risen Monstrosity Cuffs" },
            [178699] = { itemName = "Sapgorger Belt" },
            [178731] = { itemName = "Viscera-Stitched Footpads" },
            [178736] = { itemName = "Stitchflesh's Misplaced Signet" },
            [221189] = { itemName = "Experiment 08752's Band" },
            [178742] = { itemName = "Bottled Flayedwing Toxin" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [221159] = { itemName = "Harvester's Interdiction" },
            --R
            [212417] = { itemName = "Beyond's Dark Visage" },
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [225588] = { itemName = "Sanguine Experiment's Bandages" },
            [212425] = { itemName = "Devourer's Taut Innards" },
            [225591] = { itemName = "Fleeting Massacre Footpads" },
            [212447] = { itemName = "Key to the Unseeming" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [219915] = { itemName = "Foul Behemoth's Chelicera" },
            [212456] = { itemName = "Void Reaper's Contract" },
            [212389] = { itemName = "Spire of Transfused Horrors" },
        },
        ["Restoration"] = {
            --D
            [221077] = { itemName = '"Emergency Stop" Keychain' },
            [221088] = { itemName = "Anvilhide Cape" },
            [178741] = { itemName = "Risen Monstrosity Cuffs" },
            [178699] = { itemName = "Sapgorger Belt" },
            [178731] = { itemName = "Viscera-Stitched Footpads" },
            [178736] = { itemName = "Stitchflesh's Misplaced Signet" },
            [221189] = { itemName = "Experiment 08752's Band" },
            [178708] = { itemName = "Unbound Changeling" },
            [133304] = { itemName = "Gale of Shadows" },
            [221166] = { itemName = "Krix'vizk's Speech Rod" },
            --R
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [212438] = { itemName = "Polluted Spectre's Wraps" },
            [225583] = { itemName = "Behemoth's Eroded Cinch" },
            [212445] = { itemName = "Chitin-Spiked Jackboots" },
            [212447] = { itemName = "Key to the Unseeming" },
            [225576] = { itemName = "Writhing Ringworm" },
            [220202] = { itemName = "Spymaster's Web" },
            [220305] = { itemName = "Ovi'nax's Mercurial Egg" },
            [212397] = { itemName = "Takazj's Entropic Edict" },
            [212404] = { itemName = "Scepter of Manifested Miasma" },
            [212387] = { itemName = "Broodtwister's Grim Catalyst" },
        },
    },
    ["Evoker"] = {
        ["Devastation"] = {
            --D
            [221156] = { itemName = "Cryptbound Headpiece" },
            [221181] = { itemName = "Elder's Hemolymphal Periapt" },
            [221140] = { itemName = "Shadowblight Mantle" },
            [133363] = { itemName = "Troggstitched Drape" },
            [221147] = { itemName = "Goliath's Chitinous Chainmail" },
            [221174] = { itemName = "Penumbral Rimeguards" },
            [221080] = { itemName = "Corpseleecher Grips" },
            [221168] = { itemName = "Cinch of Lingering Influence" },
            [221186] = { itemName = "Entwined Chimeric Legguards" },
            [221152] = { itemName = "Silksteel Striders" },
            [221136] = { itemName = "Devout Zealot's Ring" },
            [159461] = { itemName = "Band of the Ancient Dredger" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [56462] = { itemName = "Gale of Shadows" },
            [221083] = { itemName = "Wardbreaker of the Fractured" },
            --R
            [212448] = { itemName = "Locket of Broken Memories" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [225581] = { itemName = "Ky'veza's Covert Clasps" },
            [225580] = { itemName = "Accelerated Ascension Coil" },
            [212435] = { itemName = "Liquified Defector's Leggings" },
            [225586] = { itemName = "Rasha'nan's Grotesque Talons" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [212447] = { itemName = "Key to the Unseeming" },
            [220202] = { itemName = "Spymaster's Web" },
            [212451] = { itemName = "Aberrant Spellforge" },
            [212397] = { itemName = "Takazj's Entropic Edict" },
        },
        ["Preservation"] = {
            --D
            [221077] = { itemName = '"Emergency Stop" Keychain' },
            [221088] = { itemName = "Anvilhide Cape" },
            [221174] = { itemName = "Penumbral Rimeguards" },
            [221162] = { itemName = "Claws of Tainted Ichor" },
            [221168] = { itemName = "Cinch of Lingering Influence" },
            [159379] = { itemName = "Sure-Foot Sabatons" },
            [159461] = { itemName = "Band of the Ancient Dredger" },
            [221136] = { itemName = "Devout Zealot's Ring" },
            [178708] = { itemName = "Unbound Changeling" },
            [133304] = { itemName = "Gale of Shadows" },
            [221083] = { itemName = "Wardbreaker of the Fractured" },
            --R
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [225575] = { itemName = "Silken Advisor's Favor" },
            [212446] = { itemName = "Royal Emblem of Nerub-ar" },
            [212415] = { itemName = "Throne Defender's Bangles" },
            [212436] = { itemName = "Clutches of Paranoia" },
            [225580] = { itemName = "Accelerated Ascension Coil" },
            [225586] = { itemName = "Rasha'nan's Grotesque Talons" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [220202] = { itemName = "Spymaster's Web" },
            [225576] = { itemName = "Writhing Ringworm" },
            [220305] = { itemName = "Ovi'nax's Mercurial Egg" },
            [212405] = { itemName = "Flawless Phase Blade" },
            [212387] = { itemName = "Broodtwister's Grim Catalyst" },
            [212397] = { itemName = "Takazj's Entropic Edict" },
        },
        ["Augmentation"] = {
            --D
            [178738] = { itemName = "Rattling Deadeye Hood" },
            [178707] = { itemName = "Trailspinner Pendant" },
            [133363] = { itemName = "Troggstitched Drape" },
            [221174] = { itemName = "Penumbral Rimeguards" },
            [221075] = { itemName = "Reinforced Anti-Intruder Chainmail" },
            [159379] = { itemName = "Sure-Foot Sabatons" },
            [162542] = { itemName = "Seal of the City Watch" },
            [133286] = { itemName = "Umbriss Band" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [159622] = { itemName = "Hadal's Nautilus" },
            [133303] = { itemName = "Staff of Siphoned Essences" },
            [221150] = { itemName = "Arachnoid Soulcleaver" },
            [221172] = { itemName = "Pail of Preserved Obscurity" },
            --R
            [212428] = { itemName = "Final Meal's Horns" },
            [212448] = { itemName = "Locket of Broken Memories" },
            [212446] = { itemName = "Royal Emblem of Nerub-ar" },
            [212415] = { itemName = "Throne Defender's Bangles" },
            [212414] = { itemName = "Lost Watcher's Remains" },
            [225586] = { itemName = "Rasha'nan's Grotesque Talons" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [225576] = { itemName = "Writhing Ringworm" },
            [220202] = { itemName = "Spymaster's Web" },
            [212454] = { itemName = "Mad Queen's Mandate" },
            [212397] = { itemName = "Takazj's Entropic Edict" },
            [212405] = { itemName = "Flawless Phase Blade" },
            [212387] = { itemName = "Broodtwister's Grim Catalyst" },
        },
    },
    ["Hunter"] = {
        ["Beast Mastery"] = {
            --D
            [178707] = { itemName = "Trailspinner Pendant" },
            [212446] = { itemName = "Royal Emblem of Nerub-ar" },
            [219342] = { itemName = "Glyph-Etched Vambraces" },
            [219341] = { itemName = "Glyph-Etched Gauntlets" },
            [221075] = { itemName = "Reinforced Anti-Intruder Chainmail" },
            [159379] = { itemName = "Sure-Foot Sabatons" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [225576] = { itemName = "Writhing Ringworm" },
            [133282] = { itemName = "Skardyn's Grace" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [212399] = { itemName = "Splintershot Silkbow" },
            --R
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [225581] = { itemName = "Ky'veza's Covert Clasps" },
            [212436] = { itemName = "Clutches of Paranoia" },
            [212017] = { itemName = "Lightless Scavenger's Bonegirdle" },
            [212022] = { itemName = "Lightless Scavenger's Footpads" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [212447] = { itemName = "Key to the Unseeming" },
            [212454] = { itemName = "Mad Queen's Mandate" },
            [212456] = { itemName = "Void Reaper's Contract" },
            [212400] = { itemName = "Shade-Touched Silencer" },
        },
        ["Marksmanship"] = {
            --D
            [178738] = { itemName = "Rattling Deadeye Hood" },
            [178707] = { itemName = "Trailspinner Pendant" },
            [133363] = { itemName = "Troggstitched Drape" },
            [221174] = { itemName = "Penumbral Rimeguards" },
            [159386] = { itemName = "Anchor Chain Girdle" },
            [133293] = { itemName = "Red Scale Boots" },
            [221136] = { itemName = "Devout Zealot's Ring" },
            [162542] = { itemName = "Seal of the City Watch" },
            [133282] = { itemName = "Skardyn's Grace" },
            [219312] = { itemName = "Empowering Crystal of Anub'ikkaj" },
            [221074] = { itemName = "Augmented Refractor Cannon" },
            --R
            [212448] = { itemName = "Locket of Broken Memories" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [225581] = { itemName = "Ky'veza's Covert Clasps" },
            [225580] = { itemName = "Accelerated Ascension Coil" },
            [212435] = { itemName = "Liquified Defector's Leggings" },
            [225586] = { itemName = "Rasha'nan's Grotesque Talons" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [225576] = { itemName = "Writhing Ringworm" },
            [221023] = { itemName = "Treacherous Transmitter" },
            [212456] = { itemName = "Void Reaper's Contract" },
            [212454] = { itemName = "Mad Queen's Mandate" },
            [212399] = { itemName = "Splintershot Silkbow" },
        },
        ["Survival"] = {
            --D
            [178707] = { itemName = "Trailspinner Pendant" },
            [133363] = { itemName = "Troggstitched Drape" },
            [221174] = { itemName = "Penumbral Rimeguards" },
            [221162] = { itemName = "Claws of Tainted Ichor" },
            [221168] = { itemName = "Cinch of Lingering Influence" },
            [159379] = { itemName = "Sure-Foot Sabatons" },
            [162542] = { itemName = "Seal of the City Watch" },
            [221141] = { itemName = "High Nerubian Signet" },
            [133282] = { itemName = "Skardyn's Grace" },
            [159623] = { itemName = "Dead-Eye Spyglass" },
            [221159] = { itemName = "Harvester's Interdiction" },
            --R
            [178707] = { itemName = "Trailspinner Pendant" },
            [222817] = { itemName = "Consecrated Cloak" },
            [212421] = { itemName = "Goresplattered Membrane" },
            [212016] = { itemName = "Lightless Scavenger's Wristguards" },
            [225580] = { itemName = "Accelerated Ascension Coil" },
            [221202] = { itemName = "Defiance Crusher's Sabatons" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [225576] = { itemName = "Writhing Ringworm" },
            [133282] = { itemName = "Skardyn's Grace" },
            [212454] = { itemName = "Mad Queen's Mandate" },
            [222448] = { itemName = "Charged Halberd" },
        },
    },
    ["Mage"] = {
        ["Arcane"] ={
            --D
            [221187] = { itemName = "Intertwiner's Shadowcowl" },
            [221077] = { itemName = '"Emergency Stop" Keychain' },
            [221135] = { itemName = "Fanatic's Blackened Shoulderwraps" },
            [221088] = { itemName = "Anvilhide Cape" },
            [221095] = { itemName = "Shadowed Orator's Tunic" },
            [221182] = { itemName = "Vitriolic Veinwoven Wraps" },
            [221170] = { itemName = "Subduer's Terrorgrips" },
            [221158] = { itemName = "Burrower's Cinch" },
            [221076] = { itemName = "E.D.N.A. Stabilizers" },
            [221082] = { itemName = "Tainted Earthshard Walkers" },
            [221136] = { itemName = "Devout Zealot's Ring" },
            [221189] = { itemName = "Experiment 08752's Band" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [219313] = { itemName = "Mereldar's Toll" },
            [221085] = { itemName = "Melodious Iron Songspire" },
            --R
            [212440] = { itemName = "Devotee's Discarded Headdress" },
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [212446] = { itemName = "Royal Emblem of Nerub-ar" },
            [225584] = { itemName = "Skeinspinner's Duplicitous Cuffs" },
            [225585] = { itemName = "Acrid Ascendant's Sash" },
            [225582] = { itemName = "Assimilated Eggshell Slippers" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [212447] = { itemName = "Key to the Unseeming" },
            [220305] = { itemName = "Ovi'nax's Mercurial Egg" },
            [220202] = { itemName = "Spymaster's Web" },
            [212397] = { itemName = "Takazj's Entropic Edict" },
        },
        ["Fire"] = {
            --D
            [221187] = { itemName = "Intertwiner's Shadowcowl" },
            [221077] = { itemName = '"Emergency Stop" Keychain'},
            [178740] = { itemName = "Reanimator's Mantle" },
            [221088] = { itemName = "Anvilhide Cape" },
            [221095] = { itemName = "Shadowed Orator's Tunic" },
            [221182] = { itemName = "Vitriolic Veinwoven Wraps" },
            [178705] = { itemName = "Tricksprite Gloves" },
            [221158] = { itemName = "Burrower's Cinch" },
            [221076] = { itemName = "E.D.N.A. Stabilizers" },
            [221082] = { itemName = "Tainted Earthshard Walkers" },
            [133299] = { itemName = "Circle of Bone" },
            [221189] = { itemName = "Experiment 08752's Band" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [133304] = { itemName = "Gale of Shadows" },
            [221166] = { itemName = "Krix'vizk's Speech Rod" },
            --R
            [212440] = { itemName = "Devotee's Discarded Headdress" },
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [225584] = { itemName = "Skeinspinner's Duplicitous Cuffs" },
            [225585] = { itemName = "Acrid Ascendant's Sash" },
            [225582] = { itemName = "Assimilated Eggshell Slippers" },
            [225576] = { itemName = "Writhing Ringworm" },
            [212447] = { itemName = "Key to the Unseeming" },
            [220305] = { itemName = "Ovi'nax's Mercurial Egg" },
            [220202] = { itemName = "Spymaster's Web" },
            [212394] = { itemName = "Sovereign's Disdain" },
            [212387] = { itemName = "Broodtwister's Grim Catalyst" },
            [212397] = { itemName = "Takazj's Entropic Edict" },
        },
        ["Frost"] = {
            --D
            [221187] = { itemName = "Intertwiner's Shadowcowl" },
            [221077] = { itemName = '"Emergency Stop" Keychain' },
            [221135] = { itemName = "Fanatic's Blackened Shoulderwraps" },
            [221154] = { itemName = "Swarmcaller's Shroud" },
            [221095] = { itemName = "Shadowed Orator's Tunic" },
            [221182] = { itemName = "Vitriolic Veinwoven Wraps" },
            [178705] = { itemName = "Tricksprite Gloves" },
            [221158] = { itemName = "Burrower's Cinch" },
            [221164] = { itemName = "Archaic Venomancer's Footwraps" },
            [221149] = { itemName = "Membranous Slippers" },
            [221136] = { itemName = "Devout Zealot's Ring" },
            [178736] = { itemName = "Stitchflesh's Misplaced Signet" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [133304] = { itemName = "Gale of Shadows" },
            [221166] = { itemName = "Krix'vizk's Speech Rod" },
            [133283] = { itemName = "Modgud's Blade" },
            [221172] = { itemName = "Pail of Preserved Obscurity" },
            --R
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [212446] = { itemName = "Royal Emblem of Nerub-ar" },
            [225584] = { itemName = "Skeinspinner's Duplicitous Cuffs" },
            [225585] = { itemName = "Acrid Ascendant's Sash" },
            [225582] = { itemName = "Assimilated Eggshell Slippers" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [212447] = { itemName = "Key to the Unseeming" },
            [220305] = { itemName = "Ovi'nax's Mercurial Egg" },
            [220202] = { itemName = "Spymaster's Web" },
            [212397] = { itemName = "Takazj's Entropic Edict" },
            [212394] = { itemName = "Sovereign's Disdain" },
            [212387] = { itemName = "Broodtwister's Grim Catalyst" },
        },
    },
    ["Monk"] = {
        ["Brewmaster"] = {
            --D
            [221181] = { itemName = "Elder's Hemolymphal Periapt" },
            [56126] = { itemName = "Azureborne Cloak" },
            [178702] = { itemName = "Bands of the Undergrowth" },
            [221180] = { itemName = "Gorebound Stranglers" },
            [221134] = { itemName = "Shadow Congregant's Belt" },
            [159320] = { itemName = "Besieger's Deckstalkers" },
            [178781] = { itemName = "Ritual Commander's Ring" },
            [56445] = { itemName = "Ring of Dun Algaz" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [219312] = { itemName = "Empowering Crystal of Anub'ikkaj" },
            [56440] = { itemName = "Skardyn's Grace" },
            [221159] = { itemName = "Harvester's Interdiction" },
            [221144] = { itemName = "Zephyrous Sail Carver" },
            [159648] = { itemName = "Bainbridge's Blackjack" },
            --R
            [225575] = { itemName = "Silken Advisor's Favor" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [225588] = { itemName = "Sanguine Experiment's Bandages" },
            [212432] = { itemName = "Thousand-Scar Impalers" },
            [212425] = { itemName = "Devourer's Taut Innards" },
            [225591] = { itemName = "Fleeting Massacre Footpads" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [225576] = { itemName = "Writhing Ringworm" },
            [212454] = { itemName = "Mad Queen's Mandate" },
            [212456] = { itemName = "Void Reaper's Contract" },
            [219915] = { itemName = "Foul Behemoth's Chelicera" },
            [212389] = { itemName = "pire of Transfused Horrors" },
            [219877] = { itemName = "oid Reaper's Warp Blade" },
            [212398] = { itemName = "Bludgeons of Blistering Wind" },
        },
        ["Mistweaver"] = {
            --D
            [221077] = { itemName = '"Emergency Stop" Keychain' },
            [221148] = { itemName = "Epaulets of the Clipped Wings" },
            [133363] = { itemName = "Troggstitched Drape" },
            [221142] = { itemName = "Scheming Assailer's Bands" },
            [159309] = { itemName = "Port Pillager's Belt" },
            [159320] = { itemName = "Besieger's Deckstalkers" },
            [133299] = { itemName = "Circle of Bone" },
            [178736] = { itemName = "Stitchflesh's Misplaced Signet" },
            [133304] = { itemName = "Gale of Shadows" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [221166] = { itemName = "Krix'vizk's Speech Rod" },
            --R
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [225588] = { itemName = "Sanguine Experiment's Bandages" },
            [225583] = { itemName = "Behemoth's Eroded Cinch" },
            [212445] = { itemName = "Chitin-Spiked Jackboots" },
            [212447] = { itemName = "Key to the Unseeming" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [219917] = { itemName = "Creeping Coagulum" },
            [212452] = { itemName = "Gruesome Syringe" },
            [212404] = { itemName = "Scepter of Manifested Miasma" },
            [212387] = { itemName = "Broodtwister's Grim Catalyst" },
        },
        ["Windwalker"] = {
            --D
            [178691] = { itemName = "Hood of the Hidden Path" },
            [221077] = { itemName = '"Emergency Stop" Keychain' },
            [221088] = { itemName = "Anvilhide Cape" },
            [178741] = { itemName = "Risen Monstrosity Cuffs" },
            [178699] = { itemName = "Sapgorger Belt" },
            [178731] = { itemName = "Viscera-Stitched Footpads" },
            [221189] = { itemName = "Experiment 08752's Band" },
            [178736] = { itemName = "Stitchflesh's Misplaced Signet" },
            [221137] = { itemName = "Black Shepherd's Guisarme" },
            [221090] = { itemName = "Eirich's Fist of Deception" },
            [221090] = { itemName = "Eirich's Fist of Deception" },
            [133282] = { itemName = "Skardyn's Grace" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            --R
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [212433] = { itemName = "Omnivore's Venomous Camouflage" },
            [212438] = { itemName = "Polluted Spectre's Wraps" },
            [225583] = { itemName = "Behemoth's Eroded Cinch" },
            [212445] = { itemName = "Chitin-Spiked Jackboots" },
            [212447] = { itemName = "Key to the Unseeming" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [212413] = { itemName = "Honored Executioner's Perforator" },
            [219877] = { itemName = "Void Reaper's Warp Blade" },
            [212409] = { itemName = "Venom-Etched Claw" },
            [221023] = { itemName = "Treacherous Transmitter" },
            [212456] = { itemName = "Void Reaper's Contract" },
        },
    },
    ["Paladin"] = {
        ["Holy"] = {
            --D
            [221181] = { itemName = "Elder's Hemolymphal Periapt" },
            [221154] = { itemName = "Swarmcaller's Shroud" },
            [221167] = { itemName = "Vociferous Subjugator's Bracers" },
            [133289] = { itemName = "Belt of the Forgemaster" },
            [221178] = { itemName = "Ichor-Stained Sollerets" },
            [178736] = { itemName = "Stitchflesh's Misplaced Signet" },
            [221189] = { itemName = "Experiment 08752's Band" },
            [133304] = { itemName = "Gale of Shadows" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [178737] = { itemName = "Amarth's Spellblade" },
            [221177] = { itemName = "Old-Blood Hielaman" },
            --R
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [212424] = { itemName = "Seasoned Earthen Boulderplates" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [225587] = { itemName = "Devoted Offering's Irons" },
            [225589] = { itemName = "Nether Bounty's Greatbelt" },
            [225590] = { itemName = "Boots of the Black Bulwark" },
            [225576] = { itemName = "Writhing Ringworm" },
            [212447] = { itemName = "Key to the Unseeming" },
            [220202] = { itemName = "Spymaster's Web" },
            [220305] = { itemName = "Ovi'nax's Mercurial Egg" },
            [212405] = { itemName = "Flawless Phase Blade" },
            [225579] = { itemName = "Crest of the Caustic Despot" },
        },
        ["Protection"] = {
            --D
            [221088] = { itemName = "Anvilhide Cape" },
            [133306] = { itemName = "Bracers of Umbral Mending" },
            [221133] = { itemName = "Girdle of Somber Ploys" },
            [221178] = { itemName = "Ichor-Stained Sollerets" },
            [133299] = { itemName = "Circle of Bone" },
            [159461] = { itemName = "Band of the Ancient Dredger" },
            [178730] = { itemName = "Engorged Worm Smasher" },
            [178712] = { itemName = "Acidslough " },
            [178694] = { itemName = "Wrathbark Greathelm" },
            [221077] = { itemName = '"Emergency Stop" Keychain' },
            --R
            [212427] = { itemName = "Visor of the Ascended Captain" },
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [212437] = { itemName = "Ravaged Lamplighter's Manacles" },
            [225589] = { itemName = "Nether Bounty's Greatbelt" },
            [225590] = { itemName = "Boots of the Black Bulwark" },
            [212447] = { itemName = "Key to the Unseeming" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [212392] = { itemName = "Duelist's Dancing Steel" },
            [225579] = { itemName = "Crest of the Caustic Despot" },
        },
        ["Retribution"] = {
            --D
            [221077] = { itemName = '"Emergency Stop" Keychain' },
            [221088] = { itemName = "Anvilhide Cape" },
            [133306] = { itemName = "Bracers of Umbral Mending" },
            [221133] = { itemName = "Girdle of Somber Ploys" },
            [221092] = { itemName = "Legplates of Broken Trust" },
            [159428] = { itemName = "Ballast Sinkers" },
            [133286] = { itemName = "Umbriss Band" },
            [162541] = { itemName = "Band of the Roving Scalawag" },
            [133300] = { itemName = "Mark of Khardros" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [133298] = { itemName = "Wild Hammer" },
            --R
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [212446] = { itemName = "Royal Emblem of Nerub-ar" },
            [225587] = { itemName = "Devoted Offering's Irons" },
            [212418] = { itemName = "Black Blood Injectors" },
            [225589] = { itemName = "Nether Bounty's Greatbelt" },
            [225590] = { itemName = "Boots of the Black Bulwark" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [225576] = { itemName = "Writhing Ringworm" },
            [212453] = { itemName = "Skyterror's Corrosive Organ" },
            [220305] = { itemName = "Ovi'nax's Mercurial Egg" },
            [212407] = { itemName = "Anub'arash's Colossal Mandible" },
        },
    },
    ["Priest"] = {
        ["Discipline"] = {
            --D
            [133302] = { itemName = "Crown of Enfeebled Bodies" },
            [221077] = { itemName = '"Emergency Stop" Keychain' },
            [221088] = { itemName = "Anvilhide Cape" },
            [221182] = { itemName = "Vitriolic Veinwoven Wraps" },
            [221158] = { itemName = "Burrower's Cinch" },
            [221082] = { itemName = "Tainted Earthshard Walkers" },
            [159461] = { itemName = "Band of the Ancient Dredger" },
            [178736] = { itemName = "Stitchflesh's Misplaced Signet" },
            [56462] = { itemName = "Gale of Shadows" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [221166] = { itemName = "Krix'vizk's Speech Rod" },
            [221165] = { itemName = "Unceremonious Bloodletter" },
            [221172] = { itemName = "Pail of Preserved Obscurity" },
            --R
            [212440] = { itemName = "Devotee's Discarded Headdress" },
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [225584] = { itemName = "Skeinspinner's Duplicitous Cuffs" },
            [225585] = { itemName = "Acrid Ascendant's Sash" },
            [225582] = { itemName = "Assimilated Eggshell Slippers" },
            [212447] = { itemName = "Key to the Unseeming" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [220202] = { itemName = "Spymaster's Web" },
            [212452] = { itemName = "Gruesome Syringe" },
            [212397] = { itemName = "Takazj's Entropic Edict" },
            [212394] = { itemName = "Sovereign's Disdain" },
            [212387] = { itemName = "Broodtwister's Grim Catalyst" },
        },
        ["Holy"] = {
            --D
            [178707] = { itemName = "Trailspinner Pendant" },
            [56126] = { itemName = "Azureborne Cloak" },
            [221176] = { itemName = "Arachnofrost Vest" },
            [178782] = { itemName = "Necropolis Lord's Shackles" },
            [221087] = { itemName = "Dorlita's Safety Belt" },
            [221149] = { itemName = "Membranous Slippers" },
            [162541] = { itemName = "Band of the Roving Scalawag" },
            [56444] = { itemName = "Umbriss Band" },
            [178708] = { itemName = "Unbound Changeling" },
            [219312] = { itemName = "Empowering Crystal of Anub'ikkaj" },
            [56137] = { itemName = "Staff of Siphoned Essences" },
            [178709] = { itemName = "Scithewood Scepter" },
            [221132] = { itemName = "Overflowing Umbral Pail" },
            --R
            [225575] = { itemName = "Silken Advisor's Favor" },
            [212446] = { itemName = "Royal Emblem of Nerub-ar" },
            [212419] = { itemName = "Bile-Soaked Harness" },
            [212426] = { itemName = "Crunchy Intruder's Wristband" },
            [225585] = { itemName = "Acrid Ascendant's Sash" },
            [212416] = { itemName = "Cosmic-Tinged Treads" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [225576] = { itemName = "Writhing Ringworm" },
            [212452] = { itemName = "Gruesome Syringe" },
            [219917] = { itemName = "Creeping Coagulum" },
            [212397] = { itemName = "Takazj's Entropic Edict" },
            [212394] = { itemName = "Sovereign's Disdain" },
            [212387] = { itemName = "Broodtwister's Grim Catalyst" },
        },
        ["Shadow"] = {
            --D
            [221077] = { itemName = '"Emergency Stop" Keychain' },
            [221088] = { itemName = "Anvilhide Cape" },
            [133295] = { itemName = "Crimsonborne Bracers" },
            [178748] = { itemName = "Gory Surgeon's Gloves" },
            [221158] = { itemName = "Burrower's Cinch" },
            [221149] = { itemName = "Membranous Slippers" },
            [221136] = { itemName = "Devout Zealot's Ring" },
            [133299] = { itemName = "Circle of Bone" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [219312] = { itemName = "Empowering Crystal of Anub'ikkaj" },
            [221085] = { itemName = "Melodious Iron Songspire" },
            --R
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [225584] = { itemName = "Skeinspinner's Duplicitous Cuffs" },
            [212441] = { itemName = "Bindings of the Starless Night" },
            [225585] = { itemName = "Acrid Ascendant's Sash" },
            [225582] = { itemName = "Assimilated Eggshell Slippers" },
            [212447] = { itemName = "Key to the Unseeming" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [220202] = { itemName = "Spymaster's Web" },
            [220305] = { itemName = "Ovi'nax's Mercurial Egg" },
            [212397] = { itemName = "Takazj's Entropic Edict" },
        },
    },
    ["Rogue"] = {
        ["Assassination"] = {
            --D
            [221077] = { itemName = '"Emergency Stop" Keychain' },
            [133363] = { itemName = "Troggstitched Drape" },
            [221157] = { itemName = "Unbreakable Beetlebane Bindings" },
            [133353] = { itemName = "Troggbone Cinch" },
            [221169] = { itemName = "Whisperer's Echoing Steps" },
            [56444] = { itemName = "Umbriss Band" },
            [162542] = { itemName = "Seal of the City Watch" },
            [159623] = { itemName = "Dead-Eye Spyglass" },
            [133282] = { itemName = "Skardyn's Grace" },
            [221183] = { itemName = "Splice 'n Dice" },
            [221138] = { itemName = "Parson's Ornamented Blade" },
            --R
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [225588] = { itemName = "Sanguine Experiment's Bandages" },
            [225583] = { itemName = "Behemoth's Eroded Cinch" },
            [225591] = { itemName = "Fleeting Massacre Footpads" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [225576] = { itemName = "Writhing Ringworm" },
            [221023] = { itemName = "Treacherous Transmitter" },
            [212456] = { itemName = "Void Reaper's Contract" },
            [225636] = { itemName = "Regicide" },
            [212395] = { itemName = "Blood-Kissed Kukri" },
        },
        ["Outlaw"] = {
            --D
            [221181] = { itemName = "Elder's Hemolymphal Periapt" },
            [221154] = { itemName = "Swarmcaller's Shroud" },
            [221142] = { itemName = "Scheming Assailer's Bands" },
            [178699] = { itemName = "Sapgorger Belt" },
            [133354] = { itemName = "Glimmerthread Pantaloons" },
            [178731] = { itemName = "Viscera-Stitched Footpads" },
            [178736] = { itemName = "Stitchflesh's Misplaced Signet" },
            [221189] = { itemName = "Experiment 08752's Band" },
            [159623] = { itemName = "Dead-Eye Spyglass" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [221144] = { itemName = "Zephyrous Sail Carver" },
            [221183] = { itemName = "Splice 'n Dice" },
            --R
            [212448] = { itemName = "Locket of Broken Memories" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [225588] = { itemName = "Sanguine Experiment's Bandages" },
            [225583] = { itemName = "Behemoth's Eroded Cinch" },
            [212423] = { itemName = "Rebel's Drained Marrowslacks" },
            [212445] = { itemName = "Chitin-Spiked Jackboots" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [212447] = { itemName = "Key to the Unseeming" },
            [212456] = { itemName = "Void Reaper's Contract" },
            [212454] = { itemName = "Mad Queen's Mandate" },
            [219877] = { itemName = "Void Reaper's Warp Blade" },
            [212395] = { itemName = "Blood-Kissed Kukri" },
        },
        ["Subtlety"] = {
            --D
            [221163] = { itemName = "Whispering Mask" },
            [178707] = { itemName = "Trailspinner Pendant" },
            [221175] = { itemName = "Shadowchill Amice" },
            [133292] = { itemName = "Azureborne Cloak" },
            [178744] = { itemName = "Freshly Embalmed Jerkin" },
            [221157] = { itemName = "Unbreakable Beetlebane Bindings" },
            [159328] = { itemName = "Wharf Warden's Gloves" },
            [133353] = { itemName = "Troggbone Cinch" },
            [221153] = { itemName = "Gauzewoven Legguards" },
            [159320] = { itemName = "Besieger's Deckstalkers" },
            [221141] = { itemName = "High Nerubian Signet" },
            [133287] = { itemName = "Ring of Dun Algaz" },
            [159623] = { itemName = "Dead-Eye Spyglass" },
            [219312] = { itemName = "Empowering Crystal of Anub'ikkaj" },
            [178743] = { itemName = "Stitchflesh's Scalpel" },
            [178743] = { itemName = "Stitchflesh's Scalpel" },
            --R
            [212417] = { itemName = "Beyond's Dark Visage" },
            [225575] = { itemName = "Silken Advisor's Favor" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [225588] = { itemName = "Sanguine Experiment's Bandages" },
            [212425] = { itemName = "Devourer's Taut Innards" },
            [225591] = { itemName = "Fleeting Massacre Footpads" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [225576] = { itemName = "Writhing Ringworm" },
            [212456] = { itemName = "Void Reaper's Contract" },
            [221023] = { itemName = "Treacherous Transmitter" },
            [212395] = { itemName = "Blood-Kissed Kukri" },
        },
    },
    ["Shaman"] = {
        ["Elemental"] = {
            --D
            [133285] = { itemName = "Wildhammer Riding Helm" },
            [221077] = { itemName = '"Emergency Stop" Keychain' },
            [178695] = { itemName = "Wintersnap Shoulderguards" },
            [221088] = { itemName = "Anvilhide Cape" },
            [221147] = { itemName = "Goliath's Chitinous Chainmail" },
            [159372] = { itemName = "Dread Captain's Irons" },
            [221162] = { itemName = "Claws of Tainted Ichor" },
            [159386] = { itemName = "Anchor Chain Girdle" },
            [221186] = { itemName = "Entwined Chimeric Legguards" },
            [133293] = { itemName = "Red Scale Boots" },
            [178736] = { itemName = "Stitchflesh's Misplaced Signet" },
            [159461] = { itemName = "Band of the Ancient Dredger" },
            [178708] = { itemName = "Unbound Changeling" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [221083] = { itemName = "Wardbreaker of the Fractured" },
            [221165] = { itemName = "Unceremonious Bloodletter" },
            [178750] = { itemName = "Encrusted Canopic Lid" },
            --R
            [212428] = { itemName = "Final Meal's Horns" },
            [212448] = { itemName = "Locket of Broken Memories" },
            [221667] = { itemName = "Consecrated Cloak" },
            [225581] = { itemName = "Ky'veza's Covert Clasps" },
            [212414] = { itemName = "Lost Watcher's Remains" },
            [225586] = { itemName = "Rasha'nan's Grotesque Talons" },
            [212447] = { itemName = "Key to the Unseeming" },
            [225576] = { itemName = "Writhing Ringworm" },
            [220305] = { itemName = "Ovi'nax's Mercurial Egg" },
            [220202] = { itemName = "Spymaster's Web" },
            [212394] = { itemName = "Sovereign's Disdain" },
            [225579] = { itemName = "Crest of the Caustic Despot" },
        },
        ["Enhancement"] = {
            --D
            [221156] = { itemName = "Cryptbound Headpiece" },
            [221077] = { itemName = '"Emergency Stop" Keychain' },
            [178695] = { itemName = "Wintersnap Shoulderguards" },
            [221088] = { itemName = "Anvilhide Cape" },
            [221147] = { itemName = "Goliath's Chitinous Chainmail" },
            [178703] = { itemName = "Hiveswarm Bracers" },
            [221162] = { itemName = "Claws of Tainted Ichor" },
            [221075] = { itemName = "Reinforced Anti-Intruder Chainmail" },
            [221186] = { itemName = "Entwined Chimeric Legguards" },
            [221152] = { itemName = "Silksteel Striders" },
            [133299] = { itemName = "Circle of Bone" },
            [178736] = { itemName = "Stitchflesh's Misplaced Signet" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [133282] = { itemName = "Skardyn's Grace" },
            [219312] = { itemName = "Empowering Crystal of Anub'ikkaj" },
            [221090] = { itemName = "Eirich's Fist of Deception" },
            [159648] = { itemName = "Bainbridge's Blackjack" },
            --R
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [212446] = { itemName = "Royal Emblem of Nerub-ar" },
            [212421] = { itemName = "Goresplattered Membrane" },
            [212415] = { itemName = "Throne Defender's Bangles" },
            [212414] = { itemName = "Lost Watcher's Remains" },
            [225586] = { itemName = "Rasha'nan's Grotesque Talons" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [212447] = { itemName = "Key to the Unseeming" },
            [221023] = { itemName = "Treacherous Transmitter" },
            [220305] = { itemName = "Ovi'nax's Mercurial Egg" },
            [212456] = { itemName = "Void Reaper's Contract" },
            [219877] = { itemName = "Void Reaper's Warp Blade" },
            [212398] = { itemName = "Bludgeons of Blistering Wind" },
        },
        ["Restoration"] = {
            --D
            [212448] = { itemName = "Locket of Broken Memories" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [225581] = { itemName = "Ky'veza's Covert Clasps" },
            [225580] = { itemName = "Accelerated Ascension Coil" },
            [212435] = { itemName = "Liquified Defector's Leggings" },
            [178745] = { itemName = "Striders of Restless Malice" },
            [221136] = { itemName = "Devout Zealot's Ring" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [220202] = { itemName = "Spymaster's Web" },
            [56462] = { itemName = "Gale of Shadows" },
            [221083] = { itemName = "Wardbreaker of the Fractured" },
            [212394] = { itemName = "Sovereign's Disdain" },
            [225579] = { itemName = "Crest of the Caustic Despot" },
            --R
            [212448] = { itemName = "Locket of Broken Memories" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [225581] = { itemName = "Ky'veza's Covert Clasps" },
            [225580] = { itemName = "Accelerated Ascension Coil" },
            [212435] = { itemName = "Liquified Defector's Leggings" },
            [225586] = { itemName = "Rasha'nan's Grotesque Talons" },
            [225576] = { itemName = "Writhing Ringworm" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [220202] = { itemName = "Spymaster's Web" },
            [220305] = { itemName = "Ovi'nax's Mercurial Egg" },
            [212397] = { itemName = "Takazj's Entropic Edict" },
            [212394] = { itemName = "Sovereign's Disdain" },
            [225579] = { itemName = "Crest of the Caustic Despot" },
        },
    },
    ["Warlock"] = {
        ["Affliction"] = {
            --D
            [221077] = { itemName = '"Emergency Stop" Keychain' },
            [221088] = { itemName = "Anvilhide Cape" },
            [133295] = { itemName = "Crimsonborne Bracers" },
            [221158] = { itemName = "Burrower's Cinch" },
            [221149] = { itemName = "Membranous Slippers" },
            [221136] = { itemName = "Devout Zealot's Ring" },
            [133299] = { itemName = "Circle of Bone" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [219312] = { itemName = "Empowering Crystal of Anub'ikkaj" },
            [221085] = { itemName = "Melodious Iron Songspire" },
            --R
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [225584] = { itemName = "Skeinspinner's Duplicitous Cuffs" },
            [225585] = { itemName = "Acrid Ascendant's Sash" },
            [212416] = { itemName = "Cosmic-Tinged Treads" },
            [212447] = { itemName = "Key to the Unseeming" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [220202] = { itemName = "Spymaster's Web" },
            [212454] = { itemName = "Mad Queen's Mandate" },
            [212397] = { itemName = "Takazj's Entropic Edict" },
        },
        ["Demonology"] = {
            --D
            [133302] = { itemName = "Crown of Enfeebled Bodies" },
            [221077] = { itemName = '"Emergency Stop" Keychain' },
            [221088] = { itemName = "Anvilhide Cape" },
            [133295] = { itemName = "Crimsonborne Bracers" },
            [221158] = { itemName = "Burrower's Cinch" },
            [221149] = { itemName = "Membranous Slippers" },
            [221136] = { itemName = "Devout Zealot's Ring" },
            [133299] = { itemName = "Circle of Bone" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [219312] = { itemName = "Empowering Crystal of Anub'ikkaj" },
            [221085] = { itemName = "Melodious Iron Songspire" },
            --R
            [212440] = { itemName = "Devotee's Discarded Headdress" },
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [225584] = { itemName = "Skeinspinner's Duplicitous Cuffs" },
            [225585] = { itemName = "Acrid Ascendant's Sash" },
            [212416] = { itemName = "Cosmic-Tinged Treads" },
            [212447] = { itemName = "Key to the Unseeming" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [220202] = { itemName = "Spymaster's Web" },
            [220305] = { itemName = "Ovi'nax's Mercurial Egg" },
            [212397] = { itemName = "Takazj's Entropic Edict" },
        },
        ["Destruction"] = {
            --D
            [133302] = { itemName = "Crown of Enfeebled Bodies" },
            [221077] = { itemName = '"Emergency Stop" Keychain' },
            [221088] = { itemName = "Anvilhide Cape" },
            [133295] = { itemName = "Crimsonborne Bracers" },
            [221158] = { itemName = "Burrower's Cinch" },
            [221149] = { itemName = "Membranous Slippers" },
            [221136] = { itemName = "Devout Zealot's Ring" },
            [133299] = { itemName = "Circle of Bone" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [133304] = { itemName = "Gale of Shadows" },
            [221085] = { itemName = "Melodious Iron Songspire" },
            --R
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [225584] = { itemName = "Skeinspinner's Duplicitous Cuffs" },
            [225585] = { itemName = "Acrid Ascendant's Sash" },
            [212416] = { itemName = "Cosmic-Tinged Treads" },
            [212447] = { itemName = "Key to the Unseeming" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [220202] = { itemName = "Spymaster's Web" },
            [212454] = { itemName = "Mad Queen's Mandate" },
            [212397] = { itemName = "Takazj's Entropic Edict" },
        },
    },
    ["Warrior"] = {
        ["Arms"] = {
            --D
            [178694] = { itemName = "Wrathbark Greathelm" },
            [178707] = { itemName = "Trailspinner Pendant" },
            [221185] = { itemName = "Flesh Connector's Epaulets" },
            [221088] = { itemName = "Anvilhide Cape" },
            [221161] = { itemName = "Experimental Goresilk Chestguard" },
            [221167] = { itemName = "Vociferous Subjugator's Bracers" },
            [221086] = { itemName = "Machinist's Searing Handguards" },
            [133289] = { itemName = "Belt of the Forgemaster" },
            [178701] = { itemName = "Gormshell Greaves" },
            [159428] = { itemName = "Ballast Sinkers" },
            [133299] = { itemName = "Circle of Bone" },
            [159461] = { itemName = "Band of the Ancient Dredger" },
            [219300] = { itemName = "Skarmorak Shard" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [221184] = { itemName = "Surgical Heartstopper" },
            --R
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [212437] = { itemName = "Ravaged Lamplighter's Manacles" },
            [212418] = { itemName = "Black Blood Injectors" },
            [225589] = { itemName = "Nether Bounty's Greatbelt" },
            [212447] = { itemName = "Key to the Unseeming" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [225590] = { itemName = "Boots of the Black Bulwark" },
            [212454] = { itemName = "Mad Queen's Mandate" },
            [221023] = { itemName = "Treacherous Transmitter" },
            [212407] = { itemName = "Anub'arash's Colossal Mandible" },
        },
        ["Fury"] = {
            --D
            [178777] = { itemName = "Darkfrost Helmet" },
            [221077] = { itemName = '"Emergency Stop" Keychain' },
            [133294] = { itemName = "Earthshape Pauldrons" },
            [221088] = { itemName = "Anvilhide Cape" },
            [221161] = { itemName = "Experimental Goresilk Chestguard" },
            [221167] = { itemName = "Vociferous Subjugator's Bracers" },
            [159429] = { itemName = "Rope-Scored Gauntlets" },
            [221133] = { itemName = "Girdle of Somber Ploys" },
            [178701] = { itemName = "Gormshell Greaves" },
            [159428] = { itemName = "Ballast Sinkers" },
            [133286] = { itemName = "Umbriss Band" },
            [221141] = { itemName = "High Nerubian Signet" },
            [219300] = { itemName = "Skarmorak Shard" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [133298] = { itemName = "Wild Hammer" },
            --R
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [212446] = { itemName = "Royal Emblem of Nerub-ar" },
            [212437] = { itemName = "Ravaged Lamplighter's Manacles" },
            [212442] = { itemName = "Greatbelt of the Hungerer" },
            [225576] = { itemName = "Writhing Ringworm" },
            [225590] = { itemName = "Boots of the Black Bulwark" },
            [212454] = { itemName = "Mad Queen's Mandate" },
            [221023] = { itemName = "Treacherous Transmitter" },
            [212388] = { itemName = "Ulgrax's Morsel-Masher" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
        },
        ["Protection"] = {
            --D
            [221077] = { itemName = '"Emergency Stop" Keychain' },
            [178749] = { itemName = "Vile Butcher's Pauldrons" },
            [221088] = { itemName = "Anvilhide Cape" },
            [221167] = { itemName = "Vociferous Subjugator's Bracers" },
            [221133] = { itemName = "Girdle of Somber Ploys" },
            [221178] = { itemName = "Ichor-Stained Sollerets" },
            [221136] = { itemName = "Devout Zealot's Ring" },
            [159461] = { itemName = "Band of the Ancient Dredger" },
            [178751] = { itemName = "Spare Meat Hook" },
            [219314] = { itemName = "Ara-Kara Sacbrood" },
            [221145] = { itemName = "Shipwrecker's Bludgeon" },
            [178712] = { itemName = "Acidslough Bulwark" },
            --R
            [212443] = { itemName = "Shattershell Greaves" },
            [225577] = { itemName = "Sureki Zealot's Insignia" },
            [225574] = { itemName = "Wings of Shattered Sorrow" },
            [212437] = { itemName = "Ravaged Lamplighter's Manacles" },
            [220305] = { itemName = "Ovi'nax's Mercurial Egg" },
            [225589] = { itemName = "Nether Bounty's Greatbelt" },
            [212447] = { itemName = "Key to the Unseeming" },
            [225578] = { itemName = "Seal of the Poisoned Pact" },
            [212450] = { itemName = "Swarmlord's Authority" },
            [212392] = { itemName = "Duelist's Dancing Steel" },
            [225579] = { itemName = "Crest of the Caustic Despot" },
        },
    }
}